[package]
name = "system-zero-core"
version = "0.0.1"
authors = ["Matthew O'Connor <thegreendragon@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.10.0"

[build-dependencies]
lalrpop = "0.10.0"

[[bin]]
doc = false
test = false
name = "main"
path = "src/main.rs"
